package parser

var PlayerTypesMapping = map[string]string{
	"1": "Lineman",
	"2": "Catcher",
	"3": "Thrower",
	"4": "Blitzer",
	"5": "Ogre",

	"6":  "Long Beard",
	"7":  "Runner",
	"8":  "Blitzer",
	"9":  "Troll Slayer",
	"10": "Deathroller",

	"11": "Lineman",
	"12": "Catcher",
	"13": "Thrower",
	"14": "Wardancer",
	"15": "Treeman",

	"16": "Lineman",
	"17": "Thrower",
	"18": "Gutter Runner",
	"19": "Stormvermin",
	"20": "Rat Ogre",

	"21": "Lineman",
	"22": "Goblin",
	"23": "Thrower",
	"24": "Black Orc Blocker",
	"25": "Blitzer",
	"26": "Troll",

	"27": "Skink",
	"28": "Saurus",
	"29": "Kroxigor",

	"32": "Beastman",
	"33": "Chaos Warrior",
	"34": "Minotaur",

	"30":  "Goblin",
	"31":  "Looney",
	"44":  "Troll",
	"45":  "Pogoer",
	"46":  "Fanatic",
	"107": "Bombardier",

	"47": "Lineman",
	"48": "Runner",
	"49": "Assassin",
	"50": "Blitzer",
	"51": "Witch Elf",

	"54": "Skeleton",
	"55": "Zombie",
	"56": "Ghoul",
	"57": "Wight",
	"58": "Mummie",

	"60": "Halfling",
	"61": "Treeman",

	"62": "Lineman",
	"63": "Trower",
	"64": "Runner",
	"65": "Berserker",
	"66": "Norse Werewolf",
	"67": "Yhetee",

	"68": "Lineman",
	"69": "Thrower",
	"70": "Catcher",
	"71": "Blitzer",

	"72": "Lineman",
	"73": "Thrower",
	"74": "Catcher",
	"75": "Blitzer",

	"77": "Lineman",
	"78": "Thrower",
	"79": "Catcher",
	"80": "Blitzer",

	"81": "Skeleton",
	"82": "Thro Ra",
	"83": "Blitz Ra",
	"84": "Tomb Guardian",

	"86": "Zombie",
	"87": "Ghoul",
	"88": "Wight",
	"89": "Flesh Golem",
	"90": "Werewolf",

	"94": "Beast Of Nurgle",
	"92": "Pestigor",
	"93": "Nurgle Warrior",
	"91": "Rotter",

	"95": "Snotling",
	"96": "Ogre",

	"97": "Thrall",
	"98": "Vampire",

	"108": "Hobgoblin",
	"109": "Blocker",
	"110": "Bull Centaur",
	"111": "Minotaur",

	"123": "Goblin",
	"124": "Skaven Lineman",
	"125": "Skaven Thrower",
	"126": "Skaven Blitzer",
	"127": "Warpstone Troll",

	"139": "Lineman",
	"140": "Blitzer",
	"141": "Blocker",

	"142": "Lineman",
	"143": "Catcher",
	"144": "Blitzer",
	"145": "Tame Bear",
}

var SkillMapping = map[string]string{
	"1":   "Strip Ball",
	"2":   "Strength",
	"3":   "Agility",
	"4":   "Movement",
	"5":   "Armor Value",
	"6":   "Catch",
	"7":   "Dodge",
	"8":   "Sprint",
	"9":   "Pass Block",
	"10":  "Foul Appearance",
	"11":  "Leap",
	"12":  "Extra Arms",
	"13":  "Mighty Blow",
	"14":  "Leader",
	"15":  "Horns",
	"16":  "Two Heads",
	"17":  "Stand Firm",
	"18":  "Always Hungry",
	"19":  "Regeneration",
	"20":  "Take Root",
	"21":  "Accurate",
	"22":  "Break Tackle",
	"23":  "Sneaky Git",
	"25":  "Chainsaw",
	"26":  "Dauntless",
	"27":  "Dirty Player",
	"28":  "Diving Catch",
	"29":  "Dump Off",
	"30":  "Block",
	"31":  "Bone Head",
	"32":  "Very Long Legs",
	"33":  "Disturbing Presence",
	"34":  "Diving Tackle",
	"35":  "Fend",
	"36":  "Frenzy",
	"37":  "Grab",
	"38":  "Guard",
	"39":  "Hail Mary Pass",
	"40":  "Juggernaut",
	"41":  "Jump Up",
	"44":  "Loner",
	"45":  "Nerves Of Steel",
	"46":  "No Hands",
	"47":  "Pass",
	"48":  "Piling On",
	"49":  "Prehensile Tail",
	"50":  "Pro",
	"51":  "Really Stupid",
	"52":  "Right Stuff",
	"53":  "Safe Throw",
	"54":  "Secret Weapon",
	"55":  "Shadowing",
	"56":  "Side Step",
	"57":  "Tackle",
	"58":  "Strong Arm",
	"59":  "Stunty",
	"60":  "Sure Feet",
	"61":  "Sure Hands",
	"63":  "Thick Skull",
	"64":  "Throw Teammate",
	"67":  "Wild Animal",
	"68":  "Wrestle",
	"69":  "Tentacles",
	"70":  "Multiple Block",
	"71":  "Kick",
	"72":  "Kick Off Return",
	"74":  "Big Hands",
	"75":  "Claws",
	"76":  "Ball n Chain",
	"77":  "Stab",
	"78":  "Hypnotic Gaze",
	"80":  "Bombardier",
	"81":  "Decay",
	"82":  "Nurgle's Rot",
	"84":  "Blood Lust",
	"83":  "Titchy",
	"86":  "Animosity",
	"228": "Fan Favorite",
	"264": "Stakes",
}

var RaceMapping = map[string]string{
	"1":  "Human",
	"2":  "Dwarf",
	"3":  "Skaven",
	"4":  "Orc",
	"5":  "Lizardman",
	"6":  "Goblin",
	"7":  "Wood_Elf",
	"8":  "Chaos",
	"9":  "Dark_Elf",
	"10": "Undead",
	"11": "Halfling",
	"12": "Norse",
	"13": "Amazon",
	"14": "Elf",
	"15": "High_Elf",
	"16": "Khemri",
	"17": "Necromantic",
	"18": "Nurgle",
	"19": "Ogre",
	"20": "Vampire",
	"21": "Chaos_Dwarf",
	"22": "Underworld",
	"24": "Bretonnia",
	"25": "Kislev",
}

var CasualtyMapping = map[string]string{
	"1":  "Badly Hurt",
	"2":  "Broken Ribs",
	"3":  "Groin Strain",
	"4":  "Gouged Eye",
	"5":  "Broken Jaw",
	"6":  "Fractured Arm",
	"7":  "Fractured Leg",
	"8":  "Smashed Hand",
	"9":  "Pinched Nerve",
	"10": "Damaged Back",
	"11": "Smashed Knee",
	"12": "Smashed Hip",
	"13": "Smashed Ankle",
	"14": "Serious Concussion",
	"15": "Fractured Skull",
	"16": "Broken Neck",
	"17": "Smashed Collar Bone",
	"18": "Death",
}
